---

- name: run "apt-get update"
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install required packages
  become: yes
  apt:
    name: 
      - python3-pip
      - python3-venv
    state: present

- name: remove conflicting packages
  become: yes
  apt:
    name: 
      - python3-virtualenv
    state: absent
    autoremove: yes

- name: upgrade pip
  pip:
    name: 
      - pip
      - virtualenv
      - virtualenvwrapper
    state: latest