---
- name: Run "apt-get update"
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install zsh
  become: yes
  apt:
    name: zsh
    state: present

- name: check if zsh is the current shell
  set_fact:
    zsh_is_default: "{{ true if ansible_env.SHELL is search('zsh') else false }}"

- name: get zsh path
  command: which zsh
  register: zsh_path
  when: not zsh_is_default

- name: change default shell for user
  become: true
  user:
    name: "{{ username }}"
    shell: "{{ zsh_path.stdout }}"
  when: not zsh_is_default

- name: copy default zsh config
  blockinfile:
    path: "{{ shell_default_rc_file }}"
    content: "{{ lookup('template', '.zshrc.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK zsh config"
    insertbefore: BOF

- name: include pip role to fix virtualenvwrapper settings
  include_role:
    name: pip
    tasks_from: configure


- name: check if virtualenv is installed
  shell: "bash -c typeset -F | grep virtualenvwrapper"
  register: result
  check_mode: no
  ignore_errors: true

- name: restore previous virtualenvwrapper settings
  blockinfile:
    path: "/home/{{ username }}/.zshrc"
    block: |
      export WORKON_HOME=/home/{{ username }}/.virtualenvs
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
      source /home/{{ username }}/.local/bin/virtualenvwrapper.sh
    # validate: "source %s"
    marker: "# {mark} ANSIBLE MANAGED BLOCK virtualenvwrapper"
  when: result.rc == 0