---

- block:
  - include_tasks: install.yml
  tags:
    - zsh:install

- block:
  - include_tasks: configure.yml
  tags:
    - zsh:configure

- block:
  - include_tasks: oh-my-zsh.yml
  tags:
    - zsh:oh-my-zsh

- block:
  - include_tasks: oh-my-zsh-configure.yml
  tags:
    - zsh:oh-my-zsh:configure
