---
- name: update packages cache
  become: yes
  apt:
    update_cache: yes

- name: install base packages
  become: yes
  apt:
    pkg:
    - git
    - htop
    - npm
    - curl
    - jq
    - ipcalc
    - arp-scan
    - net-tools
    - traceroute

- name: Install nodejs packages
  become: yes
  npm:
    name: gtop
    global: yes
