---
- name: install terminator
  become: yes
  apt:
    name: terminator
    state: present
    
- name: ensure terminator config folder
  file:
    path: "{{ ansible_env.HOME }}/.config/terminator/"
    state: directory
    mode: '0700'
    
- name: copy terminator config
  copy:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/terminator/config"
